import pygame
 
# Tamanho do Jogo
COLUNAS = 10
LINHAS = 20
TAM_CELULA = 40
LARGURA_JOGO, ALTURA_JOGO = COLUNAS * TAM_CELULA, LINHAS * TAM_CELULA

# Tamanho da Barra Lateral
SIDEBAR_LARG = 200
ALTURA_PREVIEW = 0.7
SCORE_PREVIEW = 1 - ALTURA_PREVIEW

# Janela
PADDING = 20
LARG_JANELA = LARGURA_JOGO + SIDEBAR_LARG + PADDING * 3
ALT_JANELA = ALTURA_JOGO + PADDING * 2

# Cores
CINZA = '#1C1C1C'
WHITE = '#FFFFFF'
